### ISSUE TITLE
Please, publish to open-vsx.org

### ISSUE THREAD

**Issue by stone-w4tch3r** [wenfangdu/quick-new#3]
Hello! First of all, thanks for awesome extension!

I am using VSCodium, and it uses dedicated (and FOSS) extensions marketplace, [open-vsx.org](url)
May you consider publishing there?
It is compatible with default VS marketplace ;-)

For now it is needed to install raw .vsix file

[https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace](url)
[https://github.com/eclipse/openvsx/wiki/Publishing-Extensions](url)

**Comment by wenfangdu** [comment]
@stone-w4tch3r Thanks for reporting, I've published it [here](https://open-vsx.org/extension/wenfangdu/faster-new), please let me know if there's any issue.
